### ISSUE TITLE
read_string(efs) tries to read on s3

### ISSUE THREAD

**Issue by geertvandeweyer** [geertvandeweyer/cromwell#1]
the following wf fails on output evaluation: 

`

## GPU machine, different queue ++ Volatile run
workflow Test_35 {
    
    String efs_datadir = "/mnt/efs/Test_Files/cacheRef/Test_35"

    # some runtime metrics
    call get_metrics {
        input:
            efs_datadir = efs_datadir
    }
    
    output {
        File gpu = get_metrics.out_gpu
        String gpu_info = get_metrics.gpu_info
    }
    
}

task get_metrics {
    input {
        String efs_datadir
    }
    String lcb = "{"
    String rcb = "}"
    command {
        set -euo pipefail
        
        apt-get update -y >/dev/null
        apt-get install -y pciutils >/dev/null

        mkdir -p ~{efs_datadir}

        # gpu
        lspci | grep -i vga > ~{efs_datadir}/gpu.txt

    }
    output {
        File out_gpu = "~{efs_datadir}/gpu.txt"
        String gpu_info = read_string("~{efs_datadir}/gpu.txt")
    }
    runtime {
        docker: "public.ecr.aws/lts/ubuntu:latest"
        gpuCount: "1"
    }
}
`

Error : 
`
2024-12-20 08:14:21 cromwell-system-akka.dispatchers.engine-dispatcher-15 INFO  - WorkflowManagerActor: Workflow 1fe25ad6-a7ea-40bd-9054-359dc54c126d failed (during ExecutingWorkflowState): cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor$$anon$3: Failed to evaluate job outputs:
Bad output 'get_metrics.gpu_info': Failed to read_string("/mnt/efs/Test_Files/cacheRef/Test_35/gpu.txt") (reason 1 of 1): [Attempted 1 time(s)] - IOException: Could not read from s3://cromwell-temp-uza-eu-west-2/cromwell-execution/Test_34/1fe25ad6-a7ea-40bd-9054-359dc54c126d/call-get_metrics/mnt/efs/Test_Files/cacheRef/Test_35/gpu.txt: s3://s3.amazonaws.com/cromwell-temp-uza-eu-west-2/cromwell-execution/Test_34/1fe25ad6-a7ea-40bd-9054-359dc54c126d/call-get_metrics/mnt/efs/Test_Files/cacheRef/Test_35/gpu.txt
        at cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor.$anonfun$handleExecutionSuccess$1(AwsBatchAsyncBackendJobExecutionActor.scala:1105)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

`

**Comment by geertvandeweyer** [comment]
Fixed in pr55
